// configWriter.js — VS Code settings → ~/.config/mem-watchdog/config.sh
// ─────────────────────────────────────────────────────────────────────────────
// Called from activate() and onDidChangeConfiguration(). Translates the
// extension's VS Code settings into bash variable assignments that mem-watchdog.sh
// sources at startup (after its own defaults, so these override them).
//
// Why write a file instead of passing flags?
//   The daemon is a long-running systemd service that re-reads state at
//   each loop iteration via sourced variables at startup. A file drop is the
//   simplest, restartless way to push new threshold values.
//
// Config path: $XDG_CONFIG_HOME/mem-watchdog/config.sh  (~/.config/… default)
// ─────────────────────────────────────────────────────────────────────────────
'use strict';

const fs   = require('fs');
const path = require('path');
const os   = require('os');

const XDG_CONFIG = process.env.XDG_CONFIG_HOME || path.join(os.homedir(), '.config');
const CONFIG_DIR  = path.join(XDG_CONFIG, 'mem-watchdog');
const CONFIG_FILE = path.join(CONFIG_DIR, 'config.sh');

/**
 * Write (or overwrite) the config file from current VS Code settings.
 *
 * @param {import('vscode').WorkspaceConfiguration} cfg
 *        vscode.workspace.getConfiguration('memWatchdog')
 */
function writeConfig(cfg) {
    const sigtermPct = cfg.get('sigtermThresholdPct');
    const sigkillPct = cfg.get('sigkillThresholdPct');
    const psiPct     = cfg.get('psiThresholdPct');
    // Settings are in MB (user-friendly); daemon expects KB
    const warnKB     = cfg.get('vscodeRssWarnMB')      * 1024;
    const emergKB    = cfg.get('vscodeRssEmergencyMB') * 1024;

    const lines = [
        '# Auto-generated by Mem Watchdog VS Code extension.',
        '# Do not edit manually — changes will be overwritten on next VS Code startup.',
        '# To adjust thresholds, use VS Code Settings > Mem Watchdog.',
        `SIGTERM_THRESHOLD=${sigtermPct}`,
        `SIGKILL_THRESHOLD=${sigkillPct}`,
        `PSI_THRESHOLD=${psiPct}`,
        `VSCODE_RSS_WARN_KB=${warnKB}`,
        `VSCODE_RSS_EMERG_KB=${emergKB}`,
    ];

    fs.mkdirSync(CONFIG_DIR, { recursive: true });
    fs.writeFileSync(CONFIG_FILE, lines.join('\n') + '\n', { encoding: 'utf8', mode: 0o644 });
}

module.exports = { writeConfig, CONFIG_FILE };
