// configWriter.js — VS Code settings → ~/.config/mem-watchdog/config.sh
// ─────────────────────────────────────────────────────────────────────────────
// Called from activate() and onDidChangeConfiguration(). Translates the
// extension's VS Code settings into bash variable assignments that mem-watchdog.sh
// sources at startup (after its own defaults, so these override them).
//
// Why write a file instead of passing flags?
//   The daemon is a long-running systemd service that re-reads state at
//   each loop iteration via sourced variables at startup. A file drop is the
//   simplest, restartless way to push new threshold values.
//
// Config path: $XDG_CONFIG_HOME/mem-watchdog/config.sh  (~/.config/… default)
// ─────────────────────────────────────────────────────────────────────────────
'use strict';

const fs   = require('fs');
const path = require('path');
const os   = require('os');

const XDG_CONFIG = process.env.XDG_CONFIG_HOME || path.join(os.homedir(), '.config');
const CONFIG_DIR  = path.join(XDG_CONFIG, 'mem-watchdog');
const CONFIG_FILE = path.join(CONFIG_DIR, 'config.sh');

/**
 * Write (or overwrite) the config file from current VS Code settings.
 * Validates cross-field constraints that the JSON schema cannot enforce:
 *   - sigkillThresholdPct must be strictly less than sigtermThresholdPct
 * Invalid combinations are silently corrected to safe defaults and logged
 * to the developer console. The returned object lists any corrections made
 * so the caller can optionally surface a warning to the user.
 *
 * @param {import('vscode').WorkspaceConfiguration} cfg
 *        vscode.workspace.getConfiguration('memWatchdog')
 * @returns {{ warnings: string[], changed: boolean }}
 */
function writeConfig(cfg) {
    let sigtermPct = cfg.get('sigtermThresholdPct');
    let sigkillPct = cfg.get('sigkillThresholdPct');
    const psiPct   = cfg.get('psiThresholdPct');
    let rssWarnMB  = cfg.get('vscodeRssWarnMB', 3400);
    let rssEmergMB = cfg.get('vscodeRssEmergencyMB', 3800);
    const interactiveKillEnabled = cfg.get('interactiveKillApproval.enabled', true);
    const interactiveKillDeferSeconds = cfg.get('interactiveKillApproval.deferSeconds', 120);

    // ── Cross-field validation ─────────────────────────────────────────────
    // VS Code Settings UI enforces per-field min/max, but direct settings.json
    // edits or Settings Sync from another machine can produce invalid combos.
    const warnings = [];

    if (sigkillPct >= sigtermPct) {
        warnings.push(
            `sigkillThresholdPct (${sigkillPct}%) must be < sigtermThresholdPct (${sigtermPct}%). ` +
            `Reverting both to defaults (sigterm=25, sigkill=15).`
        );
        sigtermPct = 25;
        sigkillPct = 15;
    }

    if (rssWarnMB >= rssEmergMB) {
        warnings.push(
            `vscodeRssEmergencyMB (${rssEmergMB}) must be > vscodeRssWarnMB (${rssWarnMB}). ` +
            `Reverting both to defaults (warn=3400, emergency=3800).`
        );
        rssWarnMB = 3400;
        rssEmergMB = 3800;
    }

    for (const w of warnings) {
        console.error('[memWatchdog] configWriter: ' + w);
    }

    const lines = [
        '# Auto-generated by Mem Watchdog VS Code extension.',
        '# Do not edit manually — changes will be overwritten on next VS Code startup.',
        '# To adjust thresholds, use VS Code Settings > Mem Watchdog.',
        `SIGTERM_THRESHOLD=${sigtermPct}`,
        `SIGKILL_THRESHOLD=${sigkillPct}`,
        `PSI_THRESHOLD=${psiPct}`,
        `VSCODE_RSS_WARN_KB=${rssWarnMB * 1024}`,
        `VSCODE_RSS_EMERG_KB=${rssEmergMB * 1024}`,
        `INTERACTIVE_KILL_PROMPT_ENABLED=${interactiveKillEnabled ? 1 : 0}`,
        `INTERACTIVE_KILL_DEFER_DEFAULT_S=${Math.max(30, Math.min(900, Math.floor(interactiveKillDeferSeconds)))}`,
    ];

    const newContent = lines.join('\n') + '\n';

    // Detect whether the config file actually changed.  If the on-disk content
    // is identical, skip the write and report changed=false so the caller can
    // avoid an unnecessary daemon restart.
    let changed = true;
    try {
        const existing = fs.readFileSync(CONFIG_FILE, 'utf8');
        if (existing === newContent) { changed = false; }
    } catch {
        // File missing or unreadable → will be (re-)created below.
    }

    if (changed) {
        fs.mkdirSync(CONFIG_DIR, { recursive: true });
        fs.writeFileSync(CONFIG_FILE, newContent, { encoding: 'utf8', mode: 0o644 });
    }

    return { warnings, changed };
}

module.exports = { writeConfig, CONFIG_FILE };
