// configWriter.js — VS Code settings → ~/.config/mem-watchdog/config.sh
// ─────────────────────────────────────────────────────────────────────────────
// Called from activate() and onDidChangeConfiguration(). Translates the
// extension's VS Code settings into bash variable assignments that mem-watchdog.sh
// sources at startup (after its own defaults, so these override them).
//
// Why write a file instead of passing flags?
//   The daemon is a long-running systemd service that re-reads state at
//   each loop iteration via sourced variables at startup. A file drop is the
//   simplest, restartless way to push new threshold values.
//
// Config path: $XDG_CONFIG_HOME/mem-watchdog/config.sh  (~/.config/… default)
// ─────────────────────────────────────────────────────────────────────────────
'use strict';

const fs   = require('fs');
const path = require('path');
const os   = require('os');

const XDG_CONFIG = process.env.XDG_CONFIG_HOME || path.join(os.homedir(), '.config');
const CONFIG_DIR  = path.join(XDG_CONFIG, 'mem-watchdog');
const CONFIG_FILE = path.join(CONFIG_DIR, 'config.sh');

/**
 * Write (or overwrite) the config file from current VS Code settings.
 * Validates cross-field constraints that the JSON schema cannot enforce:
 *   - sigkillThresholdPct must be strictly less than sigtermThresholdPct
 *   - vscodeRssWarnMB must be strictly less than vscodeRssEmergencyMB
 * Invalid combinations are silently corrected to safe defaults and logged
 * to the developer console. The returned array lists any corrections made
 * so the caller can optionally surface a warning to the user.
 *
 * @param {import('vscode').WorkspaceConfiguration} cfg
 *        vscode.workspace.getConfiguration('memWatchdog')
 * @returns {string[]}  — empty if all values valid; one entry per correction
 */
function writeConfig(cfg) {
    let sigtermPct = cfg.get('sigtermThresholdPct');
    let sigkillPct = cfg.get('sigkillThresholdPct');
    const psiPct   = cfg.get('psiThresholdPct');
    // Settings are in MB (user-friendly); daemon expects KB
    let warnMB     = cfg.get('vscodeRssWarnMB');
    let emergMB    = cfg.get('vscodeRssEmergencyMB');

    // ── Cross-field validation ─────────────────────────────────────────────
    // VS Code Settings UI enforces per-field min/max, but direct settings.json
    // edits or Settings Sync from another machine can produce invalid combos.
    const warnings = [];

    if (sigkillPct >= sigtermPct) {
        warnings.push(
            `sigkillThresholdPct (${sigkillPct}%) must be < sigtermThresholdPct (${sigtermPct}%). ` +
            `Reverting both to defaults (sigterm=25, sigkill=15).`
        );
        sigtermPct = 25;
        sigkillPct = 15;
    }

    if (warnMB >= emergMB) {
        warnings.push(
            `vscodeRssWarnMB (${warnMB} MB) must be < vscodeRssEmergencyMB (${emergMB} MB). ` +
            `Reverting both to defaults (warn=2500, emerg=3500).`
        );
        warnMB = 2500;
        emergMB = 3500;
    }

    for (const w of warnings) {
        console.error('[memWatchdog] configWriter: ' + w);
    }

    const warnKB  = warnMB  * 1024;
    const emergKB = emergMB * 1024;

    const lines = [
        '# Auto-generated by Mem Watchdog VS Code extension.',
        '# Do not edit manually — changes will be overwritten on next VS Code startup.',
        '# To adjust thresholds, use VS Code Settings > Mem Watchdog.',
        `SIGTERM_THRESHOLD=${sigtermPct}`,
        `SIGKILL_THRESHOLD=${sigkillPct}`,
        `PSI_THRESHOLD=${psiPct}`,
        `VSCODE_RSS_WARN_KB=${warnKB}`,
        `VSCODE_RSS_EMERG_KB=${emergKB}`,
    ];

    fs.mkdirSync(CONFIG_DIR, { recursive: true });
    fs.writeFileSync(CONFIG_FILE, lines.join('\n') + '\n', { encoding: 'utf8', mode: 0o644 });
    return warnings; // empty array = all values valid
}

module.exports = { writeConfig, CONFIG_FILE };
